server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hexaware

    username: root
    password: 2004
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1053567966731-ithlcrllo1pq7nnpgk8tublr2fltqvd5.apps.googleusercontent.com
            client-secret: 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
            scope: openid, profile, email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

jwt:
  secret: "u8Jk3n2lKj8s9d8f7g6h5j4k3l2m1n0b9v8c7x6z5a4s3d2f1g0h9j8k7l6m5n4b3"
  expiration: 86400000

  logging:
    level:
      org.springframework.web: DEBUG